image: mono:latest

cache:
  paths:
  - ~/.local/share/NuGet/Cache
  - ~/.nuget/packages

before_script:
   - apt-get update; apt-get -yq install git; apt-get -yq install vim; apt-get -yq install nunit

# Stages
stages:
  - build
  - test

build:
  stage: build
  script:
    # Restore Dependencies (NuGet)
    - nuget restore HomeBudget/Expenses.sln 
    # Build Project
    -  msbuild HomeBudget/Tests/Tests.csproj

test:
  stage: test
  script:
  - nunit-console HomeBudget/Tests/bun/debug/Tests.dll