variables:
  SOLUTION_NAME: "Tests"
  TESTPROJECT_NAME: "Tests"
before_script:
  - echo "starting build for %SOLUTION_NAME%"
  - echo "Restoring NuGet Packages..."
  - d:\tools\nuget restore "%SOLUTION_NAME%.sln"
stages:
  - build
  - test
build:
  stage: build
  script:
  - echo "Release build..."
  - '"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%SOLUTION_NAME%.sln"'
  artifacts:
    untracked: true
test:
  stage: test
  script:
  - echo "starting tests"
  - cd %TESTPROJECT_NAME%/bin/Release
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" /testcontainer:%TESTPROJECT_NAME%.dll'
  dependencies:
  - build