image: mono:latest

cache:
  paths:
  - ~/.local/share/NuGet/Cache
  - ~/.nuget/packages

before_script:
   - apt-get update; apt-get -yq install git; apt-get -yq install vim; apt-get -yq install nunit

# Stages
stages:
  - test

test:
  stage: test
  script:
    # Restore Dependencies (NuGet)
    - nuget restore /builds/Pavel-Lit/HomeBudget/Expenses.sln 
    # Build Project
    - msbuild /builds/Pavel-Lit/HomeBudget/Tests/Tests.csproj
	- nunit-console /builds/Pavel-Lit/HomeBudget/Tests/bin/Debug/Tests.dll  