image: microsoft/dotnet

variables:
  SOLUTION_NAME: "Expenses"
  TESTPROJECT_NAME: "Tests"
  MsBuildPath: "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\msbuild.exe"
  NugetPath: "C:\\Gitlab-Runner\\NuGet\\nuget.exe"

before_script:
  - echo "starting build for %SOLUTION_NAME%"
  - echo "Restoring NuGet Packages..."
  - '"%NugetPath%" restore "%SOLUTION_NAME%.sln"'
stages:
  - build
  - test
build:
  stage: build
  script:
  - echo "Release build..."
  - '"%MsBuildPath%" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%SOLUTION_NAME%.sln"'
  artifacts:
    untracked: true
test:
  stage: test
  script:
  - echo "starting tests"
  - cd %TESTPROJECT_NAME%/bin/Release
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" /testcontainer:%TESTPROJECT_NAME%.dll'
  dependencies:
  - build